# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  verify:
    desc: Run tests, lints and other verifications
    cmds:
      - rm -rf cat-launcher/src/generated-types
      - cargo test --manifest-path cat-launcher/src-tauri/Cargo.toml
      - pnpm --prefix cat-launcher format
      - pnpm --prefix cat-launcher lint:fix
      - pnpm --prefix cat-launcher lint
