// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameVariant } from "./GameVariant";

export type BackupEntry = { id: bigint, game_variant: GameVariant, release_version: string, timestamp: bigint, };
