// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameVariant } from "./GameVariant";
import type { ReleaseType } from "./ReleaseType";

export type GameRelease = { variant: GameVariant, version: string, release_type: ReleaseType, is_ready_to_play: boolean, };
