// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameVariant } from "./GameVariant";
import type { Link } from "./Link";

export type GameVariantInfo = { id: GameVariant, name: string, links: Array<Link>, };
