// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameReleaseStatus = "NotAvailable" | "NotDownloaded" | "Corrupted" | "NotInstalled" | "ReadyToPlay" | "Unknown";
