// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallationProgressStatus } from "./InstallationProgressStatus";

export type InstallationProgressPayload = { status: InstallationProgressStatus, release_id: string, };
