// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StockMod } from "./StockMod";
import type { ThirdPartyMod } from "./ThirdPartyMod";

export type Mod =
  | { type: "Stock"; content: StockMod }
  | { type: "ThirdParty"; content: ThirdPartyMod };
