// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameVariant } from "./GameVariant";
import type { Mod } from "./Mod";
import type { ModsUpdateStatus } from "./ModsUpdateStatus";

export type ModsUpdatePayload = {
  variant: GameVariant;
  mods: Array<Mod>;
  status: ModsUpdateStatus;
};
