// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorTheme } from "./ColorTheme";
import type { Font } from "./Font";

export type Settings = {
  font: Font | null;
  color_theme: ColorTheme | null;
};
