// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameVariant } from "./GameVariant";
import type { SoundpackInstallProgressStatus } from "./SoundpackInstallProgressStatus";

export type SoundpackInstallStatusPayload = { status: SoundpackInstallProgressStatus, variant: GameVariant, soundpack_id: string, };
