// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StockSoundpack } from "./StockSoundpack";
import type { ThirdPartySoundpack } from "./ThirdPartySoundpack";

export type Soundpack = { "type": "stock" } & StockSoundpack | { "type": "third-party" } & ThirdPartySoundpack;
