// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SoundpackInstallStatus } from "./SoundpackInstallStatus";

export type ThirdPartySoundpack = { id: string, name: string, description: string, owner: string, repo: string, branch: string, internal_path: string, status: SoundpackInstallStatus, last_updated_time: string | null, installed_last_updated_time: string | null, };
