// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModActivity } from "./ModActivity";
import type { ModInstallation } from "./ModInstallation";

export type ThirdPartyMod = {
  id: string;
  name: string;
  description: string;
  category: string;
  installation: ModInstallation;
  activity: ModActivity | null;
};
