// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SoundpackActivity } from "./SoundpackActivity";
import type { SoundpackInstallation } from "./SoundpackInstallation";

export type ThirdPartySoundpack = {
  id: string;
  name: string;
  installation: SoundpackInstallation;
  activity: SoundpackActivity;
};
