// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TilesetActivity } from "./TilesetActivity";
import type { TilesetInstallation } from "./TilesetInstallation";

export type ThirdPartyTileset = {
  id: string;
  name: string;
  installation: TilesetInstallation;
  activity: TilesetActivity;
};
