pub const DEFAULT_MAX_BACKUPS: u16 = 5;
pub const DEFAULT_PARALLEL_REQUESTS: u16 = 4;
pub const MIN_MAX_BACKUPS: u16 = 0;
pub const MAX_MAX_BACKUPS: u16 = 20;
pub const MIN_PARALLEL_REQUESTS: u16 = 1;
pub const MAX_PARALLEL_REQUESTS: u16 = 16;
