// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a single achievement in the game.
 */
export type Achievement = { 
/**
 * The unique identifier of the achievement.
 */
id: string, 
/**
 * The display name of the achievement.
 */
name: string, };
