// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameVariant } from "./GameVariant";

/**
 * Represents a single backup entry in the repository.
 */
export type BackupEntry = { 
/**
 * Unique identifier for the backup entry.
 */
id: bigint, 
/**
 * The game variant this backup belongs to.
 */
game_variant: GameVariant, 
/**
 * The version of the release when the backup was created.
 */
release_version: string, 
/**
 * Unix timestamp when the backup was created.
 */
timestamp: bigint, };
