// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Achievement } from "./Achievement";

/**
 * Represents the achievements earned by a specific character.
 */
export type CharacterAchievements = { 
/**
 * The name of the character.
 */
characterName: string, 
/**
 * The list of achievements earned by this character.
 */
achievements: Array<Achievement>, };
