// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the progress of a file download.
 */
export type DownloadProgress = { 
/**
 * The number of bytes already downloaded.
 */
bytes_downloaded: bigint, 
/**
 * The total number of bytes to be downloaded.
 */
total_bytes: bigint, };
