// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a font available on the system.
 */
export type Font = { 
/**
 * The display name of the font.
 */
name: string, 
/**
 * The absolute path to the font file.
 */
path: string, };
