// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for the `Exit` game event.
 */
export type GameExitPayload = { 
/**
 * The exit code of the game process, if available.
 */
code: number | null, };
