// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for the `Error` game event.
 */
export type GameErrorPayload = { 
/**
 * The error message.
 */
message: string, };
