// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the different variants of the game supported by the launcher.
 */
export type GameVariant = "DarkDaysAhead" | "BrightNights" | "TheLastGeneration";
