// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the type of activity associated with a mod.
 */
export type ModActivity = { "activity_type": "github_commit", github: string, };
