// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the installation status of a mod.
 */
export type ModInstallationStatus = "Installed" | "NotInstalled";
