// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents mod installation information.
 */
export type ModInstallation = { 
/**
 * The URL to download the mod from.
 */
download_url: string, 
/**
 * The mod information JSON or similar structure.
 */
modinfo: string, };
