// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorTheme } from "./ColorTheme";
import type { Font } from "./Font";

/**
 * Represents the application-wide settings.
 */
export type Settings = { 
/**
 * The selected font for the game.
 */
font: Font | null, 
/**
 * The selected color theme for the game.
 */
color_theme: ColorTheme | null, };
