// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about the activity and origin of a third-party soundpack.
 */
export type SoundpackActivity = { 
/**
 * The type of activity or project status.
 */
activity_type: string, 
/**
 * An optional link to the GitHub repository.
 */
github: string | null, };
