// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Details about the installation of a third-party soundpack.
 */
export type SoundpackInstallation = { 
/**
 * The URL where the soundpack archive can be downloaded.
 */
download_url: string, 
/**
 * The relative path to the soundpack directory within the archive.
 */
soundpack: string, };
