// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a stock tileset included with the game.
 */
export type StockTileset = { 
/**
 * The unique identifier for the tileset.
 */
id: string, 
/**
 * The display name of the tileset.
 */
name: string, };
