// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a stock soundpack included with the game.
 */
export type StockSoundpack = { 
/**
 * The unique identifier for the soundpack.
 */
id: string, 
/**
 * The display name of the soundpack.
 */
name: string, };
