// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a stock mod included in the game release.
 */
export type StockMod = { 
/**
 * Unique identifier for the mod.
 */
id: string, 
/**
 * Name of the mod.
 */
name: string, 
/**
 * Description of the mod.
 */
description: string, 
/**
 * Category the mod belongs to.
 */
category: string, };
