// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Theme } from "./Theme";

/**
 * Represents the user's theme preference.
 */
export type ThemePreference = { 
/**
 * The selected theme.
 */
theme: Theme, };
