// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SoundpackActivity } from "./SoundpackActivity";
import type { SoundpackInstallation } from "./SoundpackInstallation";

/**
 * Represents a third-party soundpack.
 */
export type ThirdPartySoundpack = { 
/**
 * The unique identifier for the soundpack.
 */
id: string, 
/**
 * The display name of the soundpack.
 */
name: string, 
/**
 * Installation details for the soundpack.
 */
installation: SoundpackInstallation, 
/**
 * Activity information for the soundpack.
 */
activity: SoundpackActivity, };
