// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModActivity } from "./ModActivity";
import type { ModInstallation } from "./ModInstallation";

/**
 * Represents a third-party mod.
 */
export type ThirdPartyMod = { 
/**
 * Unique identifier for the mod.
 */
id: string, 
/**
 * Name of the mod.
 */
name: string, 
/**
 * Description of the mod.
 */
description: string, 
/**
 * Category the mod belongs to.
 */
category: string, 
/**
 * Installation details.
 */
installation: ModInstallation, 
/**
 * Optional activity metadata.
 */
activity: ModActivity | null, };
