// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TilesetActivity } from "./TilesetActivity";
import type { TilesetInstallation } from "./TilesetInstallation";

/**
 * Represents a third-party tileset.
 */
export type ThirdPartyTileset = { 
/**
 * The unique identifier for the tileset.
 */
id: string, 
/**
 * The display name of the tileset.
 */
name: string, 
/**
 * Installation details for the tileset.
 */
installation: TilesetInstallation, 
/**
 * Activity information for the tileset.
 */
activity: TilesetActivity, };
