// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StockTileset } from "./StockTileset";
import type { ThirdPartyTileset } from "./ThirdPartyTileset";

/**
 * Represents a tileset, which can be either a stock tileset or a third-party one.
 */
export type Tileset = { "type": "Stock", "content": StockTileset } | { "type": "ThirdParty", "content": ThirdPartyTileset };
