// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Details about the installation of a third-party tileset.
 */
export type TilesetInstallation = { 
/**
 * The URL where the tileset archive can be downloaded.
 */
download_url: string, 
/**
 * The relative path to the tileset directory within the archive.
 */
tileset: string, };
