// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the current status of the auto-update process.
 */
export type UpdateStatus = { "type": "Checking" } | { "type": "Downloading" } | { "type": "Installing" } | { "type": "UpToDate" } | { "type": "Success" } | { "type": "Failure", "payload": { error: string, } };
